title: Repositori Partitur Not Angka
description: Repositori Partitur Not Angka oleh Henri Yulianto
theme: just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/hy-site-logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/partitur/assets/images/favicon.ico"

url: https://henriyulianto.github.io/partitur
baseurl: /
source: docs
destination: docs/_site
repository: henriyulianto/partitur
# remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  solmisasi-lily: https://henriyulianto.github.iu/solmisasi-lily
  lagumisa.web.id: https://www.lagumisa.web.id
aux_links_new_tab: true

plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release.
# Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2025 Henri Yulianto. Lisensi:  <a href=\"https://github.com/henriyulianto/henriyulianto.github.io/blob/master/LICENSE\">GNU GPLv3.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Enable back to top link at footer
back_to_top: true
back_to_top_text: "Kembali ke atas"

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
#ga_tracking: UA-2709176-10
#ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)
